 /* styles.css */

/* Author: Samuel Rodriguez Medina */
/* Date: 2025-03-02 */
/* Description: Basic styling for the project */

body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
}

h1 {
    color: #333;
    text-align: center;
}

